// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Sum$ReasonApp from './Sum.bs.js'

console.log('Hello World! ' + String(Sum$ReasonApp.sum(100, 1)))

export {}
/*  Not a pure module */
