// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as ReactDOMRe from 'reason-react/src/ReactDOMRe.js'
import * as ReasonReact from 'reason-react/src/ReasonReact.js'
import * as Greeting$ReasonReactApp from './Greeting.bs.js'

ReactDOMRe.renderToElementWithId(
  ReasonReact.element(
    undefined,
    undefined,
    Greeting$ReasonReactApp.make('Poi', /* array */ [])
  ),
  'app'
)

export {}
/*  Not a pure module */
